version: "3.9"
services:
  twitter_scanner:
    build: .
    env_file: .env
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - mongo
  mongo:
    image: mongo:6.0.2
    restart: always
    ports:
      - 27017:27017
    volumes:
      - $PWD/mongodb/:/docker-entrypoint-initdb.d
      - $PWD/dbdata:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGO_INITDB_ROOT_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD=$MONGO_INITDB_ROOT_PASSWORD
      - MONGO_INITDB_DATABASE=twitter-scanner
networks:
  app-network:
    driver: bridge