version: "3.9"
services:
  twitter_scanner:
    build: .
    env_file: .env
    restart: always
    ports:
      - "3000:3000"
  db:
    image: mysql:8.0.30
    command: --default-authentication-plugin=mysql_native_password
    container_name: db
    ports:
      - "3306:3306"
    restart: always
    env_file: .env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD
      - MYSQL_USER=$MYSQL_USER
      - MYSQL_PASSWORD=$MYSQL_PASSWORD
      - MYSQL_DATABASE=$MYSQL_DATABASE
    networks:
      - app-network
networks:
  app-network:
    driver: bridge